Fix getIfPresentObjectNonStringTest
The test `getIfPresentObjectNonStringTest` failed with the following
error:

  error: [IncompatibleArgumentType] Argument 'path' should not be
  passed to this method. Its type Path is not compatible with the
  required type: String.

The updated code of the websession cache used in the HA-plugin already
used an empty Object() instead of a Path-object. This change adapts this
change to this plugin, which fixes the failing test.

Change-Id: I2f383b13a0cb5c421e4326eaac872daf1b0849ef